/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jarSampleApp;

import jarSampleLib.Library;

public class App {
    public String getGreeting() {
    	
    	new Library().someLibraryMethod();
    	
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
